M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu22.04.1} date 2025-11-27T17:33:19+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-27T17:33:19+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X113.0Y-74.0
X113.0Y-126.0
X187.0Y-74.0
X187.0Y-126.0
M30
